name: Check KCFG numeric defaults (with report)

on:
  push:
    paths:
      - 'src/contents/kcfg/**'
      - 'util/check-kcfg-numeric-defaults.sh'
  pull_request:
    paths:
      - 'src/contents/kcfg/**'
      - 'util/check-kcfg-numeric-defaults.sh'

jobs:
  check-kcfg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure checker is executable
        run: chmod +x ./util/check-kcfg-numeric-defaults.sh

      - name: Run KCFG numeric-defaults checker and capture log
        run: |
          set -o pipefail
          ./util/check-kcfg-numeric-defaults.sh 2>&1 | tee kcfg-check.log

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kcfg-check-log
          path: kcfg-check.log